### ISSUE TITLE
Build fails on javadoc generation and FindBugs checks

### ISSUE THREAD

**Issue by juristr** [Netflix/recipes-rss#15]
Hi,

the current master branch **fails on the javadoc and FindBugs gradle tasks** when building. If I comment them, everthing else builds just fine.

Moreover, after following the [Running the RSS Reader Recipees application](https://github.com/Netflix/recipes-rss/wiki/Running-the-RSS-Reader-Recipes-application) guide and having everthing up and running, the call to http://localhost:9090/jsp/rss.jsp (as indicated) fails with this stacktrace:

```
org.apache.jasper.JasperException: PWC6033: Unable to compile class for JSP


	at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:94)
	at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:267)
	at org.apache.jasper.compiler.Compiler.generateClass(Compiler.java:318)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:360)
	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:581)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:344)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:464)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:358)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:459)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:360)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:231)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:629)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:141)
	at org.mortbay.jetty.Server.handle(Server.java:303)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:452)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:721)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:509)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:209)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:349)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:217)
	at org.mortbay.thread.BoundedThreadPool$PoolThread.run(BoundedThreadPool.java:475)
```

**Comment by simondiep** [comment]
I'm running into the exact same issue, having to comment out the build for javadocs and findbugs.  Afterwards, I get the same JasperException when going to the link http://localhost:9090/jsp/rss.jsp   I'm running on Windows 7 and Java 8.
